const Booking_Data = [
  {
    user: "u_name01",
    movie: "Avatar",
    date: "2024-01-01",
    time: "08.00pm",
    category: "Economy",
    seats: "12,13,14",
    status: "Payment Successful",
  },
  {
    user: "u_name02",
    movie: "Batman",
    date: "2024-02-01",
    time: "05.00pm",
    category: "First Class",
    seats: "1,2",
    status: "Cancel",
  },
  {
    user: "u_name03",
    movie: "Avatar",
    date: "2024-01-01",
    time: "08.00pm",
    category: "Economy",
    seats: "18,19",
    status: "Payment Pending",
  },
  {
    user: "u_name04",
    movie: "Avatar",
    date: "2024-01-01",
    time: "08.00pm",
    category: "Economy",
    seats: "30,31",
    status: "Payment Successful",
  },
  {
    user: "u_name05",
    movie: "Avatar",
    date: "2024-01-01",
    time: "08.00pm",
    category: "Economy",
    seats: "24,25",
    status: "Payment Successful",
  },
  {
    user: "u_name06",
    movie: "Avatar",
    date: "2024-01-01",
    time: "08.00pm",
    category: "Business",
    seats: "7,8",
    status: "Payment Successful",
  },
  {
    user: "u_name07",
    movie: "Avatar",
    date: "2024-01-01",
    time: "08.00pm",
    category: "First Class",
    seats: "5",
    status: "Payment Successful",
  },
  {
    user: "u_name08",
    movie: "Avatar",
    date: "2024-01-01",
    time: "08.00pm",
    category: "Business",
    seats: "13",
    status: "Payment Successful",
  },
  {
    user: "u_name09",
    movie: "Avatar",
    date: "2024-01-01",
    time: "08.00pm",
    category: "Business",
    seats: "9,10,11,12,15",
    status: "Cancel",
  },
  {
    user: "u_name10",
    movie: "Avatar",
    date: "2024-01-01",
    time: "08.00pm",
    category: "Economy",
    seats: "20,21",
    status: "Payment Successful",
  },
];

export default Booking_Data;
